apiVersion: v1
kind: Service
metadata:
  name: {{ include "fraud-check-worker.fullname" . }}
  labels:
  {{- include "fraud-check-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "fraud-check-worker.selectorLabels" . | nindent 4 }}
